# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Endercube-web
          path: build
      
      - id: WaitOnCFPages
        uses: WalshyDev/cf-pages-await@v1
        with:
            accountEmail: ${{ secrets.CF_ACCOUNT_EMAIL  }}
            apiKey: ${{ secrets.CF_API_KEY  }}
            accountId: 'c2864ddc1e0cbf6d3c92fbe97d7ff9b8'
            project: 'endercube-web'
            # Add this if you want GitHub Deployments (see below)
            githubToken: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create commit comment
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            **Build completed successfully:** ${{needs.WaitOnCFPages.outputs.success}}
            **Commit URL:** [${{needs.WaitOnCFPages.outputs.url}}](${{needs.WaitOnCFPages.outputs.url}})
            **Branch URL:** [${{needs.WaitOnCFPages.outputs.alias}}](${{needs.WaitOnCFPages.outputs.alias}})