# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Endercube-web
          path: build
      
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: 'build'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
      
      # - name: SFTP uploader
      #   uses: wangyucode/sftp-upload-action@v1.1
      #   with:
      #     host: ${{ secrets.SFTP_HOST }}
      #     port: 2022
      #     username: ${{ secrets.SFTP_USERNAME }}
      #     password: ${{ secrets.SFTP_PASSWORD }}
      #     localDir: 'build/'
      #     remoteDir: '/public/dev'
      
      - name: Upload build to hosting environment
        uses: Atyn/Simple-SFTP@0.0.2
        with:
          url: sftp://${{ secrets.SFTP_USERNAME }}:${{ secrets.SFTP_PASSWORD }}@${{ secrets.SFTP_HOST }}/public/dev
          local-directory: build

